-- ============================================
-- DSA Quest - PostgreSQL Schema
-- ============================================

-- Drop tables in dependency order so this script
-- can be safely re-run during development.

DROP TABLE IF EXISTS problems CASCADE;
DROP TABLE IF EXISTS patterns CASCADE;
DROP TABLE IF EXISTS sheets CASCADE;
DROP TABLE IF EXISTS users CASCADE;


-- ============================================
-- USERS
-- ============================================

CREATE TABLE users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);


-- ============================================
-- SHEETS
-- ============================================

CREATE TABLE sheets (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL
);


-- ============================================
-- PATTERNS
-- ============================================

CREATE TABLE patterns (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sheet_id INTEGER NOT NULL,
    source_id INTEGER,
    pattern_name VARCHAR(255) NOT NULL,
    order_number INTEGER NOT NULL,

    CONSTRAINT fk_patterns_sheet
        FOREIGN KEY (sheet_id)
        REFERENCES sheets(id)
        ON DELETE CASCADE,

    CONSTRAINT uq_patterns_sheet_order
        UNIQUE (sheet_id, order_number)
);


-- ============================================
-- PROBLEMS
-- ============================================

CREATE TABLE problems (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pattern_id INTEGER NOT NULL,

    subcategory_name TEXT,
    problem_name VARCHAR(500) NOT NULL,
    difficulty VARCHAR(20) NOT NULL,

    official_article TEXT,
    recommended_article TEXT,

    official_youtube TEXT,
    recommended_youtube TEXT,

    official_leetcode TEXT,
    recommended_leetcode TEXT,

    plus TEXT,

    official_editorial TEXT,
    recommended_editorial TEXT,

    order_number INTEGER NOT NULL,

    CONSTRAINT fk_problems_pattern
        FOREIGN KEY (pattern_id)
        REFERENCES patterns(id)
        ON DELETE CASCADE,

    CONSTRAINT uq_problems_pattern_order
        UNIQUE (pattern_id, order_number),

    CONSTRAINT chk_problem_difficulty
        CHECK (difficulty IN ('Easy', 'Medium', 'Hard'))
);


-- ============================================
-- INDEXES
-- ============================================

CREATE INDEX idx_patterns_sheet_id
    ON patterns(sheet_id);

CREATE INDEX idx_problems_pattern_id
    ON problems(pattern_id);